name: End 2 end tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SANITY_STUDIO_PROJECT_ID: ${{ secrets.SANITY_STUDIO_PROJECT_ID }}
  SANITY_STUDIO_DATASET: ${{ secrets.SANITY_STUDIO_DATASET }}
  SANITY_API_VERSION: ${{ secrets.SANITY_API_VERSION }}
  SANITY_READ_API_TOKEN: ${{ secrets.SANITY_READ_API_TOKEN }}
  SANITY_WRITE_API_TOKEN: ${{ secrets.SANITY_WRITE_API_TOKEN }}
  SANITY_SESSION_SECRET: ${{ secrets.SANITY_SESSION_SECRET }}
  SANITY_SESSION_API_TOKEN: ${{ secrets.SANITY_SESSION_API_TOKEN }}
  SANITY_STUDIO_URL: ${{ secrets.SANITY_STUDIO_URL }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        working-directory: web
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: web
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: web
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: web/playwright-report/
          retention-days: 30
